import Head from "next/head";
import Landing from "../components/sections/Landing";
import Slide from "../components/Slide";
import MainSection from "../components/MainSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Slide>
        <Landing />
      </Slide>
      <MainSection />
    </>
  );
}
